version: "3"
services:
  hub:
    image: selenium/hub:3.14
  chrome:
    image: selenium/node-chrome:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  search-module:
    image: nuclearfanta/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - MODULE=search-module.xml
    volumes:
      - ./output/search-result:/usr/share/udemy/test-output
  book-flight-module:
    image: nuclearfanta/selenium-docker
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - MODULE=book-flight-module.xml
    volumes:
    - ./output/book-result:/usr/share/udemy/test-output